[build]
builder = "nixpacks"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100

[[services]]
name = "http"
internalPort = 3001

[[services]]
name = "websocket"
internalPort = 3002
