import WebSocket from "ws";
import http from "http";
import https from "https";
import chalk from "chalk";
import { EventEmitter } from "events";

export interface TunnelConfig {
  serverUrl: string;
  wsUrl: string;
  deviceId: string;
  localPort: number;
  remotePort?: number;
  subdomain?: string;
  password?: string;
  demo?: boolean;
  authHeader?: string;
}

export interface TunnelInfo {
  id: string;
  name: string;
  url: string;
  expiresAt: string | null;
}

export class TunnelClient extends EventEmitter {
  private ws: WebSocket | null = null;

  /**
   * Local application WebSocket connections.
   *
   * wsId = browser WebSocket ID generated by the server.
   */
  private localWebSockets = new Map<string, WebSocket>();

  private config: TunnelConfig;

  private reconnectAttempts = 0;

  private maxReconnectAttempts = 10;

  private baseReconnectDelay = 1000;

  private isConnected = false;

  private tunnelInfo: TunnelInfo | null = null;

  private pingInterval: NodeJS.Timeout | null = null;

  private isReconnecting = false;

  private shouldReconnect = true;

  constructor(config: TunnelConfig) {
    super();

    this.config = config;
  }

  async connect(): Promise<TunnelInfo> {
    return new Promise((resolve, reject) => {
      this.setupWebSocket(resolve, reject);
    });
  }

  private setupWebSocket(
    resolve?: (info: TunnelInfo) => void,
    reject?: (error: Error) => void,
  ): void {
    try {
      // Clean up existing control connection
      if (this.ws) {
        this.ws.removeAllListeners();

        if (
          this.ws.readyState === WebSocket.OPEN ||
          this.ws.readyState === WebSocket.CONNECTING
        ) {
          this.ws.close();
        }
      }

      this.ws = new WebSocket(this.config.wsUrl);

      const ws = this.ws;

      ws.on("open", () => {
        this.isConnected = true;
        this.isReconnecting = false;
        this.reconnectAttempts = 0;

        this.send({
          type: "register",
          deviceId: this.config.deviceId,
          localPort: this.config.localPort,
          remotePort: this.config.remotePort,
          subdomain: this.tunnelInfo?.name || this.config.subdomain,
          password: this.config.password,
          demo: this.config.demo,
        });

        this.startPingInterval();
      });

      ws.on("message", async (data: Buffer) => {
        try {
          const message = JSON.parse(data.toString());

          await this.handleMessage(message, resolve, reject);
        } catch (error) {
          console.error("Failed to parse server message:", error);
        }
      });

      ws.on("close", () => {
        this.isConnected = false;

        this.stopPingInterval();

        this.closeAllLocalWebSockets();

        if (!this.shouldReconnect) {
          this.emit("disconnected");
          return;
        }

        if (this.reconnectAttempts < this.maxReconnectAttempts) {
          this.scheduleReconnect();
        } else {
          console.log(
            chalk.red("\nMax reconnection attempts reached. Tunnel stopped."),
          );

          console.log(
            chalk.gray("Run the command again to start a new tunnel."),
          );

          this.emit("disconnected");

          process.exit(1);
        }
      });

      ws.on("error", (error) => {
        if (!this.isConnected && !this.isReconnecting && reject) {
          reject(error);
        }

        this.emit("error", error);
      });
    } catch (error) {
      if (reject) {
        reject(error as Error);
      }
    }
  }

  private scheduleReconnect(): void {
    if (this.isReconnecting) {
      return;
    }

    this.isReconnecting = true;

    this.reconnectAttempts++;

    const delay = Math.min(
      this.baseReconnectDelay * Math.pow(2, this.reconnectAttempts - 1) +
        Math.random() * 1000,
      30000,
    );

    console.log(
      chalk.yellow(
        `\nConnection lost. Reconnecting in ${Math.round(
          delay / 1000,
        )}s... (attempt ${this.reconnectAttempts}/${this.maxReconnectAttempts})`,
      ),
    );

    setTimeout(() => {
      this.emit("reconnecting", this.reconnectAttempts);

      this.setupWebSocket();
    }, delay);
  }

  private startPingInterval(): void {
    this.stopPingInterval();

    this.pingInterval = setInterval(() => {
      if (this.isConnected && this.ws?.readyState === WebSocket.OPEN) {
        this.send({
          type: "ping",
        });
      }
    }, 15000);
  }

  private stopPingInterval(): void {
    if (this.pingInterval) {
      clearInterval(this.pingInterval);

      this.pingInterval = null;
    }
  }

  private async handleMessage(
    message: any,
    resolve?: (info: TunnelInfo) => void,
    reject?: (error: Error) => void,
  ): Promise<void> {
    switch (message.type) {
      case "registered": {
        const wasReconnect = this.tunnelInfo !== null;

        this.tunnelInfo = message.tunnel;

        this.emit("registered", message.tunnel);

        if (wasReconnect) {
          console.log(
            chalk.green(
              `\nReconnected! Tunnel restored: ${message.tunnel.url}`,
            ),
          );

          this.emit("reconnected", message.tunnel);
        } else if (resolve) {
          resolve(message.tunnel);
        }

        break;
      }

      case "request": {
        await this.handleIncomingRequest(message);

        break;
      }

      case "ws-open": {
        this.handleWebSocketOpen(message);

        break;
      }

      case "ws-message": {
        this.handleWebSocketMessage(message);

        break;
      }

      case "ws-close": {
        this.handleWebSocketClose(message);

        break;
      }

      case "error": {
        console.error(chalk.red("Server error:"), message.message);

        if (reject) {
          reject(new Error(message.message));
        }

        break;
      }

      case "pong": {
        break;
      }

      case "stopped": {
        this.emit("stopped", message.tunnelId);

        break;
      }

      default: {
        console.warn("Unknown server message:", message.type);
      }
    }
  }

  /**
   * Browser -> Server -> CLI
   *
   * Server tells CLI to create a local WebSocket.
   */
  private handleWebSocketOpen(message: any): void {
    const { wsId, path, headers } = message;

    if (!wsId) {
      return;
    }

    const safePath = path && path !== "undefined" ? path : "/";

    const localUrl = `ws://localhost:${this.config.localPort}${safePath}`;

    console.log(chalk.gray(`WebSocket opening: ${localUrl}`));

    const localHeaders: Record<string, string> = {
      host: `localhost:${this.config.localPort}`,
    };

    // Forward useful headers but remove proxy-specific ones.
    if (headers && typeof headers === "object") {
      for (const [key, value] of Object.entries(headers)) {
        if (
          typeof value === "string" &&
          ![
            "host",
            "connection",
            "upgrade",
            "sec-websocket-key",
            "sec-websocket-version",
            "sec-websocket-extensions",
            "content-length",
            "x-forwarded-host",
            "x-forwarded-proto",
            "x-forwarded-for",
          ].includes(key.toLowerCase())
        ) {
          localHeaders[key] = value;
        }
      }
    }

    const localWs = new WebSocket(localUrl, {
      headers: localHeaders,
    });

    this.localWebSockets.set(wsId, localWs);

    localWs.on("open", () => {
      console.log(chalk.gray(`WebSocket connected locally: ${wsId}`));

      this.send({
        type: "ws-opened",
        wsId,
      });
    });

    localWs.on("message", (data: Buffer, isBinary: boolean) => {
      this.send({
        type: "ws-message",
        wsId,
        data: Buffer.from(data).toString("base64"),
        binary: isBinary,
      });
    });

    localWs.on("close", () => {
      this.localWebSockets.delete(wsId);

      this.send({
        type: "ws-close",
        wsId,
      });
    });

    localWs.on("error", (error) => {
      console.error(
        chalk.red(`Local WebSocket error (${wsId}):`),
        error.message,
      );

      this.localWebSockets.delete(wsId);

      this.send({
        type: "ws-close",
        wsId,
      });
    });
  }

  /**
   * Browser -> Server -> CLI -> Local app
   */
  private handleWebSocketMessage(message: any): void {
    const { wsId, data, binary } = message;

    const localWs = this.localWebSockets.get(wsId);

    if (!localWs || localWs.readyState !== WebSocket.OPEN) {
      return;
    }

    try {
      const payload = Buffer.from(data, "base64");

      if (binary) {
        localWs.send(payload);
      } else {
        localWs.send(payload.toString("utf8"));
      }
    } catch (error) {
      console.error("Failed to forward WebSocket message:", error);
    }
  }

  /**
   * Browser -> Server -> CLI
   *
   * Close local WebSocket.
   */
  private handleWebSocketClose(message: any): void {
    const { wsId } = message;

    const localWs = this.localWebSockets.get(wsId);

    if (!localWs) {
      return;
    }

    this.localWebSockets.delete(wsId);

    if (
      localWs.readyState === WebSocket.OPEN ||
      localWs.readyState === WebSocket.CONNECTING
    ) {
      localWs.close();
    }
  }

  private closeAllLocalWebSockets(): void {
    for (const localWs of this.localWebSockets.values()) {
      if (
        localWs.readyState === WebSocket.OPEN ||
        localWs.readyState === WebSocket.CONNECTING
      ) {
        localWs.close();
      }
    }

    this.localWebSockets.clear();
  }

  private async handleIncomingRequest(message: any): Promise<void> {
    const { requestId, method, path, headers, body } = message;

    this.emit("request", {
      method,
      path,
      requestId,
    });

    const safePath = path && path !== "undefined" ? path : "/";

    const url = `http://localhost:${this.config.localPort}${safePath}`;

    const requestHeaders: Record<string, string> = {
      ...headers,
      host: `localhost:${this.config.localPort}`,
    };

    delete requestHeaders["content-length"];
    delete requestHeaders["transfer-encoding"];
    delete requestHeaders["connection"];
    delete requestHeaders["sec-fetch-site"];
    delete requestHeaders["sec-fetch-mode"];
    delete requestHeaders["sec-fetch-dest"];
    delete requestHeaders["sec-fetch-user"];
    delete requestHeaders["origin"];
    delete requestHeaders["referer"];
    delete requestHeaders["x-forwarded-host"];
    delete requestHeaders["x-forwarded-proto"];
    delete requestHeaders["x-forwarded-for"];

    if (this.config.authHeader) {
      const [key, value] = this.config.authHeader.split(": ");

      if (key && value) {
        requestHeaders[key] = value;
      }
    }

    try {
      const response = await this.makeLocalRequest(
        method,
        url,
        requestHeaders,
        body,
      );

      this.emit("response", {
        method,
        path,
        status: response.status,
        requestId,
      });

      this.send({
        type: "response",
        requestId,
        status: response.status,
        headers: response.headers,
        body: response.body,
      });
    } catch (error: any) {
      this.emit("error", error);

      this.send({
        type: "response",
        requestId,
        status: 502,
        headers: {
          "content-type": "application/json",
        },
        body: JSON.stringify({
          error: "Failed to connect to local server",
          message: error.message,
        }),
      });
    }
  }

  private makeLocalRequest(
    method: string,
    url: string,
    headers: Record<string, string>,
    body: string | null,
  ): Promise<{
    status: number;
    headers: Record<string, string>;
    body: string;
  }> {
    return new Promise((resolve, reject) => {
      const urlObj = new URL(url);

      const options: http.RequestOptions = {
        hostname: urlObj.hostname,
        port: Number(urlObj.port) || this.config.localPort,
        path: urlObj.pathname + urlObj.search,
        method,
        headers,
        timeout: 30000,
      };

      const req = http.request(options, (res) => {
        const chunks: Buffer[] = [];

        res.on("data", (chunk: Buffer) => {
          chunks.push(chunk);
        });

        res.on("end", () => {
          const bodyBuffer = Buffer.concat(chunks);

          const responseHeaders: Record<string, string> = {};

          for (const [key, value] of Object.entries(res.headers)) {
            if (value) {
              responseHeaders[key] = Array.isArray(value)
                ? value.join(", ")
                : value;
            }
          }

          delete responseHeaders["content-length"];

          delete responseHeaders["transfer-encoding"];

          delete responseHeaders["connection"];

          const contentType = responseHeaders["content-type"] || "";

          const isBinary =
            !contentType.includes("text") &&
            !contentType.includes("json") &&
            !contentType.includes("xml") &&
            !contentType.includes("javascript");

          let bodyString: string;

          if (isBinary) {
            bodyString = bodyBuffer.toString("base64");

            responseHeaders["x-body-encoding"] = "base64";
          } else {
            bodyString = bodyBuffer.toString("utf-8");
          }

          resolve({
            status: res.statusCode || 500,
            headers: responseHeaders,
            body: bodyString,
          });
        });
      });

      req.on("error", reject);

      req.on("timeout", () => {
        req.destroy();

        reject(new Error("Request timeout"));
      });

      if (body) {
        const bodyEncoding = headers?.["x-body-encoding"];

        const bodyBuffer =
          bodyEncoding === "base64"
            ? Buffer.from(body, "base64")
            : Buffer.from(body, "utf-8");

        req.write(bodyBuffer);
      }

      req.end();
    });
  }

  private send(data: any): void {
    if (this.ws?.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify(data));
    }
  }

  async stop(): Promise<void> {
    this.shouldReconnect = false;

    this.stopPingInterval();

    this.closeAllLocalWebSockets();

    if (this.tunnelInfo) {
      this.send({
        type: "stop",
        tunnelId: this.tunnelInfo.id,
      });
    }

    return new Promise((resolve) => {
      if (this.ws?.readyState === WebSocket.OPEN) {
        const timeout = setTimeout(() => resolve(), 500);

        this.ws.once("close", () => {
          clearTimeout(timeout);

          resolve();
        });

        this.ws.close();
      } else {
        resolve();
      }
    });
  }

  getTunnelInfo(): TunnelInfo | null {
    return this.tunnelInfo;
  }
}
